// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zpd.proto

package zpd_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SQLType int32

const (
	SQLType_DEFAULT      SQLType = 0
	SQLType_SHOWDATABASE SQLType = 1
	SQLType_SHOWTABLE    SQLType = 2
	SQLType_SELECT       SQLType = 3
)

var SQLType_name = map[int32]string{
	0: "DEFAULT",
	1: "SHOWDATABASE",
	2: "SHOWTABLE",
	3: "SELECT",
}

var SQLType_value = map[string]int32{
	"DEFAULT":      0,
	"SHOWDATABASE": 1,
	"SHOWTABLE":    2,
	"SELECT":       3,
}

func (x SQLType) String() string {
	return proto.EnumName(SQLType_name, int32(x))
}

func (SQLType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_04ad0942e39effdb, []int{0}
}

type Databases struct {
	Databases            []string `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Databases) Reset()         { *m = Databases{} }
func (m *Databases) String() string { return proto.CompactTextString(m) }
func (*Databases) ProtoMessage()    {}
func (*Databases) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ad0942e39effdb, []int{0}
}

func (m *Databases) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Databases.Unmarshal(m, b)
}
func (m *Databases) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Databases.Marshal(b, m, deterministic)
}
func (m *Databases) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Databases.Merge(m, src)
}
func (m *Databases) XXX_Size() int {
	return xxx_messageInfo_Databases.Size(m)
}
func (m *Databases) XXX_DiscardUnknown() {
	xxx_messageInfo_Databases.DiscardUnknown(m)
}

var xxx_messageInfo_Databases proto.InternalMessageInfo

func (m *Databases) GetDatabases() []string {
	if m != nil {
		return m.Databases
	}
	return nil
}

type NameTables struct {
	Nametables           []string `protobuf:"bytes,1,rep,name=nametables,proto3" json:"nametables,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameTables) Reset()         { *m = NameTables{} }
func (m *NameTables) String() string { return proto.CompactTextString(m) }
func (*NameTables) ProtoMessage()    {}
func (*NameTables) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ad0942e39effdb, []int{1}
}

func (m *NameTables) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameTables.Unmarshal(m, b)
}
func (m *NameTables) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameTables.Marshal(b, m, deterministic)
}
func (m *NameTables) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameTables.Merge(m, src)
}
func (m *NameTables) XXX_Size() int {
	return xxx_messageInfo_NameTables.Size(m)
}
func (m *NameTables) XXX_DiscardUnknown() {
	xxx_messageInfo_NameTables.DiscardUnknown(m)
}

var xxx_messageInfo_NameTables proto.InternalMessageInfo

func (m *NameTables) GetNametables() []string {
	if m != nil {
		return m.Nametables
	}
	return nil
}

type Item struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Val                  []byte   `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	Bool                 bool     `protobuf:"varint,3,opt,name=bool,proto3" json:"bool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ad0942e39effdb, []int{2}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Item) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *Item) GetBool() bool {
	if m != nil {
		return m.Bool
	}
	return false
}

type Row struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Row) Reset()         { *m = Row{} }
func (m *Row) String() string { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()    {}
func (*Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ad0942e39effdb, []int{3}
}

func (m *Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Row.Unmarshal(m, b)
}
func (m *Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Row.Marshal(b, m, deterministic)
}
func (m *Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Row.Merge(m, src)
}
func (m *Row) XXX_Size() int {
	return xxx_messageInfo_Row.Size(m)
}
func (m *Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Row proto.InternalMessageInfo

func (m *Row) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Rows struct {
	Rows                 []*Row   `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rows) Reset()         { *m = Rows{} }
func (m *Rows) String() string { return proto.CompactTextString(m) }
func (*Rows) ProtoMessage()    {}
func (*Rows) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ad0942e39effdb, []int{4}
}

func (m *Rows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rows.Unmarshal(m, b)
}
func (m *Rows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rows.Marshal(b, m, deterministic)
}
func (m *Rows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rows.Merge(m, src)
}
func (m *Rows) XXX_Size() int {
	return xxx_messageInfo_Rows.Size(m)
}
func (m *Rows) XXX_DiscardUnknown() {
	xxx_messageInfo_Rows.DiscardUnknown(m)
}

var xxx_messageInfo_Rows proto.InternalMessageInfo

func (m *Rows) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

type Ping struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ad0942e39effdb, []int{5}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Pong struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ServiceName          string   `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Status               *Status  `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ad0942e39effdb, []int{6}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Pong) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Pong) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ConnectionDBRequest struct {
	Dbname               string   `protobuf:"bytes,1,opt,name=dbname,proto3" json:"dbname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionDBRequest) Reset()         { *m = ConnectionDBRequest{} }
func (m *ConnectionDBRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectionDBRequest) ProtoMessage()    {}
func (*ConnectionDBRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ad0942e39effdb, []int{7}
}

func (m *ConnectionDBRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionDBRequest.Unmarshal(m, b)
}
func (m *ConnectionDBRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionDBRequest.Marshal(b, m, deterministic)
}
func (m *ConnectionDBRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionDBRequest.Merge(m, src)
}
func (m *ConnectionDBRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectionDBRequest.Size(m)
}
func (m *ConnectionDBRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionDBRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionDBRequest proto.InternalMessageInfo

func (m *ConnectionDBRequest) GetDbname() string {
	if m != nil {
		return m.Dbname
	}
	return ""
}

type CloseConnectionDBRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseConnectionDBRequest) Reset()         { *m = CloseConnectionDBRequest{} }
func (m *CloseConnectionDBRequest) String() string { return proto.CompactTextString(m) }
func (*CloseConnectionDBRequest) ProtoMessage()    {}
func (*CloseConnectionDBRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ad0942e39effdb, []int{8}
}

func (m *CloseConnectionDBRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseConnectionDBRequest.Unmarshal(m, b)
}
func (m *CloseConnectionDBRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseConnectionDBRequest.Marshal(b, m, deterministic)
}
func (m *CloseConnectionDBRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseConnectionDBRequest.Merge(m, src)
}
func (m *CloseConnectionDBRequest) XXX_Size() int {
	return xxx_messageInfo_CloseConnectionDBRequest.Size(m)
}
func (m *CloseConnectionDBRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseConnectionDBRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseConnectionDBRequest proto.InternalMessageInfo

type StatementRequest struct {
	Type                 SQLType  `protobuf:"varint,1,opt,name=type,proto3,enum=zpd.data.proto.SQLType" json:"type,omitempty"`
	Sql                  string   `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatementRequest) Reset()         { *m = StatementRequest{} }
func (m *StatementRequest) String() string { return proto.CompactTextString(m) }
func (*StatementRequest) ProtoMessage()    {}
func (*StatementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ad0942e39effdb, []int{9}
}

func (m *StatementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatementRequest.Unmarshal(m, b)
}
func (m *StatementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatementRequest.Marshal(b, m, deterministic)
}
func (m *StatementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatementRequest.Merge(m, src)
}
func (m *StatementRequest) XXX_Size() int {
	return xxx_messageInfo_StatementRequest.Size(m)
}
func (m *StatementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatementRequest proto.InternalMessageInfo

func (m *StatementRequest) GetType() SQLType {
	if m != nil {
		return m.Type
	}
	return SQLType_DEFAULT
}

func (m *StatementRequest) GetSql() string {
	if m != nil {
		return m.Sql
	}
	return ""
}

type StatementResponse struct {
	Type                 SQLType  `protobuf:"varint,1,opt,name=type,proto3,enum=zpd.data.proto.SQLType" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Status               *Status  `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatementResponse) Reset()         { *m = StatementResponse{} }
func (m *StatementResponse) String() string { return proto.CompactTextString(m) }
func (*StatementResponse) ProtoMessage()    {}
func (*StatementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ad0942e39effdb, []int{10}
}

func (m *StatementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatementResponse.Unmarshal(m, b)
}
func (m *StatementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatementResponse.Marshal(b, m, deterministic)
}
func (m *StatementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatementResponse.Merge(m, src)
}
func (m *StatementResponse) XXX_Size() int {
	return xxx_messageInfo_StatementResponse.Size(m)
}
func (m *StatementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatementResponse proto.InternalMessageInfo

func (m *StatementResponse) GetType() SQLType {
	if m != nil {
		return m.Type
	}
	return SQLType_DEFAULT
}

func (m *StatementResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *StatementResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterEnum("zpd.data.proto.SQLType", SQLType_name, SQLType_value)
	proto.RegisterType((*Databases)(nil), "zpd.data.proto.Databases")
	proto.RegisterType((*NameTables)(nil), "zpd.data.proto.NameTables")
	proto.RegisterType((*Item)(nil), "zpd.data.proto.Item")
	proto.RegisterType((*Row)(nil), "zpd.data.proto.Row")
	proto.RegisterType((*Rows)(nil), "zpd.data.proto.Rows")
	proto.RegisterType((*Ping)(nil), "zpd.data.proto.Ping")
	proto.RegisterType((*Pong)(nil), "zpd.data.proto.Pong")
	proto.RegisterType((*ConnectionDBRequest)(nil), "zpd.data.proto.ConnectionDBRequest")
	proto.RegisterType((*CloseConnectionDBRequest)(nil), "zpd.data.proto.CloseConnectionDBRequest")
	proto.RegisterType((*StatementRequest)(nil), "zpd.data.proto.StatementRequest")
	proto.RegisterType((*StatementResponse)(nil), "zpd.data.proto.StatementResponse")
}

func init() { proto.RegisterFile("zpd.proto", fileDescriptor_04ad0942e39effdb) }

var fileDescriptor_04ad0942e39effdb = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x61, 0x6f, 0xd3, 0x30,
	0x10, 0x25, 0x4b, 0xd6, 0x91, 0x6b, 0x37, 0x05, 0x0f, 0x41, 0x34, 0x21, 0x14, 0x59, 0x48, 0x94,
	0x01, 0x05, 0xca, 0x1f, 0x20, 0x6d, 0x83, 0x40, 0xaa, 0xa0, 0x73, 0x82, 0x90, 0xf8, 0xe6, 0xb4,
	0x27, 0x14, 0x29, 0x8e, 0xb3, 0xda, 0x5b, 0x19, 0x3f, 0x80, 0xdf, 0x8d, 0xec, 0xa6, 0x4a, 0x98,
	0x90, 0xa6, 0x7e, 0xca, 0xbb, 0xf3, 0xbb, 0xe7, 0x7b, 0x77, 0x31, 0xf8, 0xbf, 0xeb, 0xd5, 0xa8,
	0x5e, 0x4b, 0x2d, 0xc9, 0x89, 0x81, 0x2b, 0xae, 0xf9, 0x36, 0x3e, 0x1b, 0x2c, 0xa5, 0x10, 0xb2,
	0xda, 0x46, 0xf4, 0x05, 0xf8, 0x33, 0xae, 0x79, 0xce, 0x15, 0x2a, 0xf2, 0x04, 0xfc, 0xd5, 0x2e,
	0x08, 0x9d, 0xc8, 0x1d, 0xfa, 0xac, 0x4d, 0xd0, 0x57, 0x00, 0x5f, 0xb8, 0xc0, 0x8c, 0xe7, 0x25,
	0x2a, 0xf2, 0x14, 0xa0, 0xe2, 0x02, 0xb5, 0x8d, 0x1a, 0x72, 0x27, 0x43, 0x3f, 0x80, 0xf7, 0x59,
	0xa3, 0x20, 0x04, 0x3c, 0x7d, 0x53, 0x63, 0xe8, 0x44, 0xce, 0xf0, 0x90, 0x59, 0x4c, 0x02, 0x70,
	0xaf, 0x79, 0x19, 0x1e, 0x44, 0xce, 0x70, 0xc0, 0x0c, 0x34, 0xac, 0x5c, 0xca, 0x32, 0x74, 0x23,
	0x67, 0x78, 0x9f, 0x59, 0x4c, 0xdf, 0x81, 0xcb, 0xe4, 0x86, 0x9c, 0xc3, 0x61, 0xa1, 0x51, 0x6c,
	0xef, 0xe8, 0x8f, 0x1f, 0x8e, 0xfe, 0xf5, 0x33, 0x32, 0xb7, 0xb0, 0x2d, 0x85, 0xbe, 0x01, 0x8f,
	0xc9, 0x8d, 0x22, 0xcf, 0xc1, 0x5b, 0xcb, 0xcd, 0xae, 0xe4, 0xf4, 0x76, 0x09, 0x93, 0x1b, 0x66,
	0x09, 0xf4, 0x19, 0x78, 0x8b, 0xa2, 0xfa, 0x69, 0x9c, 0xeb, 0x42, 0xa0, 0xd2, 0x5c, 0xd4, 0xb6,
	0x55, 0x97, 0xb5, 0x09, 0xfa, 0x0b, 0xbc, 0x85, 0xbc, 0x8b, 0x45, 0x22, 0xe8, 0x2b, 0x5c, 0x5f,
	0x17, 0x4b, 0x34, 0x63, 0xb2, 0xee, 0x7c, 0xd6, 0x4d, 0x91, 0xb7, 0xd0, 0x53, 0x9a, 0xeb, 0x2b,
	0x65, 0x7d, 0xf6, 0xc7, 0xa1, 0x6d, 0xac, 0xbb, 0x8f, 0x51, 0x6a, 0xcf, 0x59, 0xc3, 0xa3, 0xaf,
	0xe1, 0x74, 0x2a, 0xab, 0x0a, 0x97, 0xba, 0x90, 0xd5, 0x6c, 0xc2, 0xf0, 0xf2, 0x0a, 0x95, 0x26,
	0x8f, 0xa0, 0xb7, 0xca, 0xcd, 0xb0, 0x6d, 0x17, 0x3e, 0x6b, 0x22, 0x7a, 0x06, 0xe1, 0xb4, 0x94,
	0x0a, 0xff, 0x53, 0x43, 0x2f, 0x20, 0x30, 0xe2, 0x28, 0xb0, 0xd2, 0x3b, 0x9d, 0x97, 0x9d, 0xe5,
	0x9c, 0x8c, 0x1f, 0xdf, 0x9e, 0x53, 0x7a, 0x31, 0xcf, 0x6e, 0x6a, 0x6c, 0xb7, 0xa6, 0x2e, 0xcb,
	0xc6, 0x97, 0x81, 0xf4, 0x8f, 0x03, 0x0f, 0x3a, 0x9a, 0xaa, 0x96, 0x95, 0xc2, 0xfd, 0x44, 0x09,
	0x78, 0xe6, 0xac, 0xf9, 0x17, 0x2c, 0xde, 0x7f, 0x4c, 0xe7, 0x53, 0x38, 0x6a, 0x64, 0x49, 0x1f,
	0x8e, 0x66, 0xc9, 0xc7, 0xf8, 0xdb, 0x3c, 0x0b, 0xee, 0x91, 0x00, 0x06, 0xe9, 0xa7, 0xaf, 0xdf,
	0x67, 0x71, 0x16, 0x4f, 0xe2, 0x34, 0x09, 0x1c, 0x72, 0x0c, 0xbe, 0xc9, 0x64, 0xf1, 0x64, 0x9e,
	0x04, 0x07, 0x04, 0xa0, 0x97, 0x26, 0xf3, 0x64, 0x9a, 0x05, 0xee, 0xe4, 0x78, 0xe1, 0xfc, 0x68,
	0xdf, 0x4d, 0xde, 0xb3, 0x9f, 0xf7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x1f, 0x56, 0x05,
	0x4b, 0x03, 0x00, 0x00,
}
