// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zpd_internal.proto

package zpd_internal_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ColumnType struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Notnull              bool     `protobuf:"varint,2,opt,name=notnull,proto3" json:"notnull,omitempty"`
	Lenght               uint64   `protobuf:"varint,3,opt,name=lenght,proto3" json:"lenght,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ColumnType) Reset()         { *m = ColumnType{} }
func (m *ColumnType) String() string { return proto.CompactTextString(m) }
func (*ColumnType) ProtoMessage()    {}
func (*ColumnType) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{0}
}

func (m *ColumnType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColumnType.Unmarshal(m, b)
}
func (m *ColumnType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColumnType.Marshal(b, m, deterministic)
}
func (m *ColumnType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColumnType.Merge(m, src)
}
func (m *ColumnType) XXX_Size() int {
	return xxx_messageInfo_ColumnType.Size(m)
}
func (m *ColumnType) XXX_DiscardUnknown() {
	xxx_messageInfo_ColumnType.DiscardUnknown(m)
}

var xxx_messageInfo_ColumnType proto.InternalMessageInfo

func (m *ColumnType) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ColumnType) GetNotnull() bool {
	if m != nil {
		return m.Notnull
	}
	return false
}

func (m *ColumnType) GetLenght() uint64 {
	if m != nil {
		return m.Lenght
	}
	return 0
}

type Column struct {
	ID                   uint64      `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 *ColumnType `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Column) Reset()         { *m = Column{} }
func (m *Column) String() string { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()    {}
func (*Column) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{1}
}

func (m *Column) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Column.Unmarshal(m, b)
}
func (m *Column) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Column.Marshal(b, m, deterministic)
}
func (m *Column) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Column.Merge(m, src)
}
func (m *Column) XXX_Size() int {
	return xxx_messageInfo_Column.Size(m)
}
func (m *Column) XXX_DiscardUnknown() {
	xxx_messageInfo_Column.DiscardUnknown(m)
}

var xxx_messageInfo_Column proto.InternalMessageInfo

func (m *Column) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Column) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Column) GetType() *ColumnType {
	if m != nil {
		return m.Type
	}
	return nil
}

type IndexInfo struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Primary              bool     `protobuf:"varint,3,opt,name=primary,proto3" json:"primary,omitempty"`
	Unique               bool     `protobuf:"varint,4,opt,name=unique,proto3" json:"unique,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexInfo) Reset()         { *m = IndexInfo{} }
func (m *IndexInfo) String() string { return proto.CompactTextString(m) }
func (*IndexInfo) ProtoMessage()    {}
func (*IndexInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{2}
}

func (m *IndexInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexInfo.Unmarshal(m, b)
}
func (m *IndexInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexInfo.Marshal(b, m, deterministic)
}
func (m *IndexInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexInfo.Merge(m, src)
}
func (m *IndexInfo) XXX_Size() int {
	return xxx_messageInfo_IndexInfo.Size(m)
}
func (m *IndexInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexInfo.DiscardUnknown(m)
}

var xxx_messageInfo_IndexInfo proto.InternalMessageInfo

func (m *IndexInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *IndexInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IndexInfo) GetPrimary() bool {
	if m != nil {
		return m.Primary
	}
	return false
}

func (m *IndexInfo) GetUnique() bool {
	if m != nil {
		return m.Unique
	}
	return false
}

type IndexColumn struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexColumn) Reset()         { *m = IndexColumn{} }
func (m *IndexColumn) String() string { return proto.CompactTextString(m) }
func (*IndexColumn) ProtoMessage()    {}
func (*IndexColumn) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{3}
}

func (m *IndexColumn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexColumn.Unmarshal(m, b)
}
func (m *IndexColumn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexColumn.Marshal(b, m, deterministic)
}
func (m *IndexColumn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexColumn.Merge(m, src)
}
func (m *IndexColumn) XXX_Size() int {
	return xxx_messageInfo_IndexColumn.Size(m)
}
func (m *IndexColumn) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexColumn.DiscardUnknown(m)
}

var xxx_messageInfo_IndexColumn proto.InternalMessageInfo

func (m *IndexColumn) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Index struct {
	ID                   uint64         `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Info                 *IndexInfo     `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Columns              []*IndexColumn `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{4}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Index) GetInfo() *IndexInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Index) GetColumns() []*IndexColumn {
	if m != nil {
		return m.Columns
	}
	return nil
}

type Table struct {
	ID                   uint64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Tbname               string    `protobuf:"bytes,2,opt,name=tbname,proto3" json:"tbname,omitempty"`
	Columns              []*Column `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	Indexes              []*Index  `protobuf:"bytes,4,rep,name=indexes,proto3" json:"indexes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{5}
}

func (m *Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table.Unmarshal(m, b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table.Marshal(b, m, deterministic)
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return xxx_messageInfo_Table.Size(m)
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Table) GetTbname() string {
	if m != nil {
		return m.Tbname
	}
	return ""
}

func (m *Table) GetColumns() []*Column {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *Table) GetIndexes() []*Index {
	if m != nil {
		return m.Indexes
	}
	return nil
}

type Schema struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Dbname               string   `protobuf:"bytes,2,opt,name=dbname,proto3" json:"dbname,omitempty"`
	Tables               []*Table `protobuf:"bytes,3,rep,name=tables,proto3" json:"tables,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schema) Reset()         { *m = Schema{} }
func (m *Schema) String() string { return proto.CompactTextString(m) }
func (*Schema) ProtoMessage()    {}
func (*Schema) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{6}
}

func (m *Schema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema.Unmarshal(m, b)
}
func (m *Schema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema.Marshal(b, m, deterministic)
}
func (m *Schema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema.Merge(m, src)
}
func (m *Schema) XXX_Size() int {
	return xxx_messageInfo_Schema.Size(m)
}
func (m *Schema) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema.DiscardUnknown(m)
}

var xxx_messageInfo_Schema proto.InternalMessageInfo

func (m *Schema) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Schema) GetDbname() string {
	if m != nil {
		return m.Dbname
	}
	return ""
}

func (m *Schema) GetTables() []*Table {
	if m != nil {
		return m.Tables
	}
	return nil
}

type SchemaRequest struct {
	Dbname               string   `protobuf:"bytes,1,opt,name=dbname,proto3" json:"dbname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemaRequest) Reset()         { *m = SchemaRequest{} }
func (m *SchemaRequest) String() string { return proto.CompactTextString(m) }
func (*SchemaRequest) ProtoMessage()    {}
func (*SchemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{7}
}

func (m *SchemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaRequest.Unmarshal(m, b)
}
func (m *SchemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaRequest.Marshal(b, m, deterministic)
}
func (m *SchemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaRequest.Merge(m, src)
}
func (m *SchemaRequest) XXX_Size() int {
	return xxx_messageInfo_SchemaRequest.Size(m)
}
func (m *SchemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaRequest proto.InternalMessageInfo

func (m *SchemaRequest) GetDbname() string {
	if m != nil {
		return m.Dbname
	}
	return ""
}

type SchemaResponse struct {
	Schema               *Schema  `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemaResponse) Reset()         { *m = SchemaResponse{} }
func (m *SchemaResponse) String() string { return proto.CompactTextString(m) }
func (*SchemaResponse) ProtoMessage()    {}
func (*SchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{8}
}

func (m *SchemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaResponse.Unmarshal(m, b)
}
func (m *SchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaResponse.Marshal(b, m, deterministic)
}
func (m *SchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaResponse.Merge(m, src)
}
func (m *SchemaResponse) XXX_Size() int {
	return xxx_messageInfo_SchemaResponse.Size(m)
}
func (m *SchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaResponse proto.InternalMessageInfo

func (m *SchemaResponse) GetSchema() *Schema {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *SchemaResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type CreateDatabaseRequest struct {
	Dbname               string   `protobuf:"bytes,1,opt,name=dbname,proto3" json:"dbname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDatabaseRequest) Reset()         { *m = CreateDatabaseRequest{} }
func (m *CreateDatabaseRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDatabaseRequest) ProtoMessage()    {}
func (*CreateDatabaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{9}
}

func (m *CreateDatabaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDatabaseRequest.Unmarshal(m, b)
}
func (m *CreateDatabaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDatabaseRequest.Marshal(b, m, deterministic)
}
func (m *CreateDatabaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDatabaseRequest.Merge(m, src)
}
func (m *CreateDatabaseRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDatabaseRequest.Size(m)
}
func (m *CreateDatabaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDatabaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDatabaseRequest proto.InternalMessageInfo

func (m *CreateDatabaseRequest) GetDbname() string {
	if m != nil {
		return m.Dbname
	}
	return ""
}

type CreateDatabaseResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDatabaseResponse) Reset()         { *m = CreateDatabaseResponse{} }
func (m *CreateDatabaseResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDatabaseResponse) ProtoMessage()    {}
func (*CreateDatabaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{10}
}

func (m *CreateDatabaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDatabaseResponse.Unmarshal(m, b)
}
func (m *CreateDatabaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDatabaseResponse.Marshal(b, m, deterministic)
}
func (m *CreateDatabaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDatabaseResponse.Merge(m, src)
}
func (m *CreateDatabaseResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDatabaseResponse.Size(m)
}
func (m *CreateDatabaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDatabaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDatabaseResponse proto.InternalMessageInfo

func (m *CreateDatabaseResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type DropDatabaseRequest struct {
	Dbname               string   `protobuf:"bytes,1,opt,name=dbname,proto3" json:"dbname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropDatabaseRequest) Reset()         { *m = DropDatabaseRequest{} }
func (m *DropDatabaseRequest) String() string { return proto.CompactTextString(m) }
func (*DropDatabaseRequest) ProtoMessage()    {}
func (*DropDatabaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{11}
}

func (m *DropDatabaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropDatabaseRequest.Unmarshal(m, b)
}
func (m *DropDatabaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropDatabaseRequest.Marshal(b, m, deterministic)
}
func (m *DropDatabaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropDatabaseRequest.Merge(m, src)
}
func (m *DropDatabaseRequest) XXX_Size() int {
	return xxx_messageInfo_DropDatabaseRequest.Size(m)
}
func (m *DropDatabaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DropDatabaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DropDatabaseRequest proto.InternalMessageInfo

func (m *DropDatabaseRequest) GetDbname() string {
	if m != nil {
		return m.Dbname
	}
	return ""
}

type DropDatabaseResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropDatabaseResponse) Reset()         { *m = DropDatabaseResponse{} }
func (m *DropDatabaseResponse) String() string { return proto.CompactTextString(m) }
func (*DropDatabaseResponse) ProtoMessage()    {}
func (*DropDatabaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{12}
}

func (m *DropDatabaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropDatabaseResponse.Unmarshal(m, b)
}
func (m *DropDatabaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropDatabaseResponse.Marshal(b, m, deterministic)
}
func (m *DropDatabaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropDatabaseResponse.Merge(m, src)
}
func (m *DropDatabaseResponse) XXX_Size() int {
	return xxx_messageInfo_DropDatabaseResponse.Size(m)
}
func (m *DropDatabaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DropDatabaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DropDatabaseResponse proto.InternalMessageInfo

func (m *DropDatabaseResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetDatabasesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDatabasesRequest) Reset()         { *m = GetDatabasesRequest{} }
func (m *GetDatabasesRequest) String() string { return proto.CompactTextString(m) }
func (*GetDatabasesRequest) ProtoMessage()    {}
func (*GetDatabasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{13}
}

func (m *GetDatabasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDatabasesRequest.Unmarshal(m, b)
}
func (m *GetDatabasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDatabasesRequest.Marshal(b, m, deterministic)
}
func (m *GetDatabasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDatabasesRequest.Merge(m, src)
}
func (m *GetDatabasesRequest) XXX_Size() int {
	return xxx_messageInfo_GetDatabasesRequest.Size(m)
}
func (m *GetDatabasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDatabasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDatabasesRequest proto.InternalMessageInfo

type GetDatabasesResponse struct {
	Databases            []string `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDatabasesResponse) Reset()         { *m = GetDatabasesResponse{} }
func (m *GetDatabasesResponse) String() string { return proto.CompactTextString(m) }
func (*GetDatabasesResponse) ProtoMessage()    {}
func (*GetDatabasesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{14}
}

func (m *GetDatabasesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDatabasesResponse.Unmarshal(m, b)
}
func (m *GetDatabasesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDatabasesResponse.Marshal(b, m, deterministic)
}
func (m *GetDatabasesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDatabasesResponse.Merge(m, src)
}
func (m *GetDatabasesResponse) XXX_Size() int {
	return xxx_messageInfo_GetDatabasesResponse.Size(m)
}
func (m *GetDatabasesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDatabasesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDatabasesResponse proto.InternalMessageInfo

func (m *GetDatabasesResponse) GetDatabases() []string {
	if m != nil {
		return m.Databases
	}
	return nil
}

func (m *GetDatabasesResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type CreateTableRequest struct {
	DBID                 uint64   `protobuf:"varint,1,opt,name=DBID,proto3" json:"DBID,omitempty"`
	Table                *Table   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTableRequest) Reset()         { *m = CreateTableRequest{} }
func (m *CreateTableRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTableRequest) ProtoMessage()    {}
func (*CreateTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{15}
}

func (m *CreateTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTableRequest.Unmarshal(m, b)
}
func (m *CreateTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTableRequest.Marshal(b, m, deterministic)
}
func (m *CreateTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTableRequest.Merge(m, src)
}
func (m *CreateTableRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTableRequest.Size(m)
}
func (m *CreateTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTableRequest proto.InternalMessageInfo

func (m *CreateTableRequest) GetDBID() uint64 {
	if m != nil {
		return m.DBID
	}
	return 0
}

func (m *CreateTableRequest) GetTable() *Table {
	if m != nil {
		return m.Table
	}
	return nil
}

type CreateTableResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTableResponse) Reset()         { *m = CreateTableResponse{} }
func (m *CreateTableResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTableResponse) ProtoMessage()    {}
func (*CreateTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{16}
}

func (m *CreateTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTableResponse.Unmarshal(m, b)
}
func (m *CreateTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTableResponse.Marshal(b, m, deterministic)
}
func (m *CreateTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTableResponse.Merge(m, src)
}
func (m *CreateTableResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTableResponse.Size(m)
}
func (m *CreateTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTableResponse proto.InternalMessageInfo

func (m *CreateTableResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetNameTablesRequest struct {
	Dbname               string   `protobuf:"bytes,1,opt,name=dbname,proto3" json:"dbname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNameTablesRequest) Reset()         { *m = GetNameTablesRequest{} }
func (m *GetNameTablesRequest) String() string { return proto.CompactTextString(m) }
func (*GetNameTablesRequest) ProtoMessage()    {}
func (*GetNameTablesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{17}
}

func (m *GetNameTablesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNameTablesRequest.Unmarshal(m, b)
}
func (m *GetNameTablesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNameTablesRequest.Marshal(b, m, deterministic)
}
func (m *GetNameTablesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNameTablesRequest.Merge(m, src)
}
func (m *GetNameTablesRequest) XXX_Size() int {
	return xxx_messageInfo_GetNameTablesRequest.Size(m)
}
func (m *GetNameTablesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNameTablesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNameTablesRequest proto.InternalMessageInfo

func (m *GetNameTablesRequest) GetDbname() string {
	if m != nil {
		return m.Dbname
	}
	return ""
}

type GetNameTablesResponse struct {
	Nametables           []string `protobuf:"bytes,1,rep,name=nametables,proto3" json:"nametables,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNameTablesResponse) Reset()         { *m = GetNameTablesResponse{} }
func (m *GetNameTablesResponse) String() string { return proto.CompactTextString(m) }
func (*GetNameTablesResponse) ProtoMessage()    {}
func (*GetNameTablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{18}
}

func (m *GetNameTablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNameTablesResponse.Unmarshal(m, b)
}
func (m *GetNameTablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNameTablesResponse.Marshal(b, m, deterministic)
}
func (m *GetNameTablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNameTablesResponse.Merge(m, src)
}
func (m *GetNameTablesResponse) XXX_Size() int {
	return xxx_messageInfo_GetNameTablesResponse.Size(m)
}
func (m *GetNameTablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNameTablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNameTablesResponse proto.InternalMessageInfo

func (m *GetNameTablesResponse) GetNametables() []string {
	if m != nil {
		return m.Nametables
	}
	return nil
}

func (m *GetNameTablesResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type DropTableRequest struct {
	DBID                 uint64   `protobuf:"varint,1,opt,name=DBID,proto3" json:"DBID,omitempty"`
	Tbname               string   `protobuf:"bytes,2,opt,name=tbname,proto3" json:"tbname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropTableRequest) Reset()         { *m = DropTableRequest{} }
func (m *DropTableRequest) String() string { return proto.CompactTextString(m) }
func (*DropTableRequest) ProtoMessage()    {}
func (*DropTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{19}
}

func (m *DropTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropTableRequest.Unmarshal(m, b)
}
func (m *DropTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropTableRequest.Marshal(b, m, deterministic)
}
func (m *DropTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropTableRequest.Merge(m, src)
}
func (m *DropTableRequest) XXX_Size() int {
	return xxx_messageInfo_DropTableRequest.Size(m)
}
func (m *DropTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DropTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DropTableRequest proto.InternalMessageInfo

func (m *DropTableRequest) GetDBID() uint64 {
	if m != nil {
		return m.DBID
	}
	return 0
}

func (m *DropTableRequest) GetTbname() string {
	if m != nil {
		return m.Tbname
	}
	return ""
}

type DropTableResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropTableResponse) Reset()         { *m = DropTableResponse{} }
func (m *DropTableResponse) String() string { return proto.CompactTextString(m) }
func (*DropTableResponse) ProtoMessage()    {}
func (*DropTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{20}
}

func (m *DropTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropTableResponse.Unmarshal(m, b)
}
func (m *DropTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropTableResponse.Marshal(b, m, deterministic)
}
func (m *DropTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropTableResponse.Merge(m, src)
}
func (m *DropTableResponse) XXX_Size() int {
	return xxx_messageInfo_DropTableResponse.Size(m)
}
func (m *DropTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DropTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DropTableResponse proto.InternalMessageInfo

func (m *DropTableResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetTableRequest struct {
	DBID                 uint64   `protobuf:"varint,1,opt,name=DBID,proto3" json:"DBID,omitempty"`
	Tbname               string   `protobuf:"bytes,2,opt,name=tbname,proto3" json:"tbname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTableRequest) Reset()         { *m = GetTableRequest{} }
func (m *GetTableRequest) String() string { return proto.CompactTextString(m) }
func (*GetTableRequest) ProtoMessage()    {}
func (*GetTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{21}
}

func (m *GetTableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTableRequest.Unmarshal(m, b)
}
func (m *GetTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTableRequest.Marshal(b, m, deterministic)
}
func (m *GetTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTableRequest.Merge(m, src)
}
func (m *GetTableRequest) XXX_Size() int {
	return xxx_messageInfo_GetTableRequest.Size(m)
}
func (m *GetTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTableRequest proto.InternalMessageInfo

func (m *GetTableRequest) GetDBID() uint64 {
	if m != nil {
		return m.DBID
	}
	return 0
}

func (m *GetTableRequest) GetTbname() string {
	if m != nil {
		return m.Tbname
	}
	return ""
}

type GetTableResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Table                *Table   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTableResponse) Reset()         { *m = GetTableResponse{} }
func (m *GetTableResponse) String() string { return proto.CompactTextString(m) }
func (*GetTableResponse) ProtoMessage()    {}
func (*GetTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b09edfbb14cca, []int{22}
}

func (m *GetTableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTableResponse.Unmarshal(m, b)
}
func (m *GetTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTableResponse.Marshal(b, m, deterministic)
}
func (m *GetTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTableResponse.Merge(m, src)
}
func (m *GetTableResponse) XXX_Size() int {
	return xxx_messageInfo_GetTableResponse.Size(m)
}
func (m *GetTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTableResponse proto.InternalMessageInfo

func (m *GetTableResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetTableResponse) GetTable() *Table {
	if m != nil {
		return m.Table
	}
	return nil
}

func init() {
	proto.RegisterType((*ColumnType)(nil), "zpd_internal.data.proto.ColumnType")
	proto.RegisterType((*Column)(nil), "zpd_internal.data.proto.Column")
	proto.RegisterType((*IndexInfo)(nil), "zpd_internal.data.proto.IndexInfo")
	proto.RegisterType((*IndexColumn)(nil), "zpd_internal.data.proto.IndexColumn")
	proto.RegisterType((*Index)(nil), "zpd_internal.data.proto.Index")
	proto.RegisterType((*Table)(nil), "zpd_internal.data.proto.Table")
	proto.RegisterType((*Schema)(nil), "zpd_internal.data.proto.Schema")
	proto.RegisterType((*SchemaRequest)(nil), "zpd_internal.data.proto.SchemaRequest")
	proto.RegisterType((*SchemaResponse)(nil), "zpd_internal.data.proto.SchemaResponse")
	proto.RegisterType((*CreateDatabaseRequest)(nil), "zpd_internal.data.proto.CreateDatabaseRequest")
	proto.RegisterType((*CreateDatabaseResponse)(nil), "zpd_internal.data.proto.CreateDatabaseResponse")
	proto.RegisterType((*DropDatabaseRequest)(nil), "zpd_internal.data.proto.DropDatabaseRequest")
	proto.RegisterType((*DropDatabaseResponse)(nil), "zpd_internal.data.proto.DropDatabaseResponse")
	proto.RegisterType((*GetDatabasesRequest)(nil), "zpd_internal.data.proto.GetDatabasesRequest")
	proto.RegisterType((*GetDatabasesResponse)(nil), "zpd_internal.data.proto.GetDatabasesResponse")
	proto.RegisterType((*CreateTableRequest)(nil), "zpd_internal.data.proto.CreateTableRequest")
	proto.RegisterType((*CreateTableResponse)(nil), "zpd_internal.data.proto.CreateTableResponse")
	proto.RegisterType((*GetNameTablesRequest)(nil), "zpd_internal.data.proto.GetNameTablesRequest")
	proto.RegisterType((*GetNameTablesResponse)(nil), "zpd_internal.data.proto.GetNameTablesResponse")
	proto.RegisterType((*DropTableRequest)(nil), "zpd_internal.data.proto.DropTableRequest")
	proto.RegisterType((*DropTableResponse)(nil), "zpd_internal.data.proto.DropTableResponse")
	proto.RegisterType((*GetTableRequest)(nil), "zpd_internal.data.proto.GetTableRequest")
	proto.RegisterType((*GetTableResponse)(nil), "zpd_internal.data.proto.GetTableResponse")
}

func init() { proto.RegisterFile("zpd_internal.proto", fileDescriptor_8d3b09edfbb14cca) }

var fileDescriptor_8d3b09edfbb14cca = []byte{
	// 625 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x4f, 0x6f, 0xda, 0x4e,
	0x10, 0xd5, 0x06, 0x63, 0xc2, 0xa0, 0x5f, 0x7e, 0xe9, 0x26, 0x50, 0xab, 0xaa, 0x52, 0xb2, 0xad,
	0x54, 0x2e, 0xa5, 0x12, 0xad, 0xd2, 0xe6, 0xd0, 0x1c, 0x12, 0xa4, 0x88, 0x4b, 0x94, 0x6e, 0x38,
	0xf5, 0xd0, 0x6a, 0x81, 0x4d, 0x41, 0xb2, 0xd7, 0x8e, 0xbd, 0x96, 0x4a, 0xaf, 0xed, 0xbd, 0x5f,
	0xa2, 0x1f, 0xb4, 0xf2, 0xfe, 0x01, 0x0c, 0x01, 0xda, 0xf8, 0xc4, 0xce, 0xf8, 0xcd, 0x7b, 0x6f,
	0x66, 0xc7, 0xc8, 0x80, 0xbf, 0x47, 0xa3, 0x2f, 0x13, 0x21, 0x79, 0x2c, 0x98, 0xdf, 0x8e, 0xe2,
	0x50, 0x86, 0xf8, 0x71, 0x2e, 0x37, 0x62, 0x92, 0xe9, 0x07, 0x4f, 0xea, 0xc3, 0x30, 0x08, 0x42,
	0xb1, 0x84, 0x27, 0x14, 0xe0, 0x22, 0xf4, 0xd3, 0x40, 0xf4, 0xa7, 0x11, 0xc7, 0x18, 0x1c, 0x39,
	0x8d, 0xb8, 0x87, 0x9a, 0xa8, 0x55, 0xa6, 0xea, 0x8c, 0x3d, 0xa8, 0x88, 0x50, 0x8a, 0xd4, 0xf7,
	0xbd, 0x9d, 0x26, 0x6a, 0xed, 0x52, 0x1b, 0xe2, 0x06, 0xb8, 0x3e, 0x17, 0x5f, 0xc7, 0xd2, 0x2b,
	0x35, 0x51, 0xcb, 0xa1, 0x26, 0x22, 0x1c, 0x5c, 0xcd, 0x89, 0xf7, 0x60, 0xa7, 0xd7, 0x55, 0x6c,
	0x0e, 0xdd, 0xe9, 0x75, 0x33, 0x7e, 0xc1, 0x02, 0xae, 0x88, 0xaa, 0x54, 0x9d, 0xf1, 0x3b, 0xa3,
	0x99, 0x71, 0xd4, 0x3a, 0xcf, 0xdb, 0x6b, 0x1a, 0x68, 0xcf, 0x6d, 0x6a, 0x63, 0x84, 0x43, 0xb5,
	0x27, 0x46, 0xfc, 0x5b, 0x4f, 0xdc, 0x86, 0x19, 0x73, 0xdf, 0x3a, 0xaf, 0x52, 0xc7, 0x76, 0xb3,
	0xa2, 0xe6, 0x41, 0x25, 0x8a, 0x27, 0x01, 0x8b, 0xa7, 0x4a, 0x70, 0x97, 0xda, 0x30, 0xeb, 0x26,
	0x15, 0x93, 0xbb, 0x94, 0x7b, 0x8e, 0x7a, 0x60, 0x22, 0x72, 0x0c, 0x35, 0x25, 0x63, 0x5a, 0xb2,
	0xa4, 0x68, 0x4e, 0x4a, 0x7e, 0x21, 0x28, 0x2b, 0xcc, 0x4a, 0xc3, 0x27, 0xe0, 0x4c, 0xc4, 0x6d,
	0xa8, 0x2c, 0xd4, 0x3a, 0x64, 0x6d, 0x73, 0xb3, 0x46, 0xa8, 0xc2, 0xe3, 0x33, 0xa8, 0x0c, 0x95,
	0x5e, 0xe2, 0x95, 0x9a, 0xa5, 0x56, 0xad, 0xf3, 0x62, 0x73, 0xa9, 0x36, 0x47, 0x6d, 0x11, 0xf9,
	0x8d, 0xa0, 0xdc, 0x67, 0x03, 0x9f, 0xaf, 0x38, 0x6a, 0x80, 0x2b, 0x07, 0x0b, 0x63, 0x31, 0x11,
	0x3e, 0x5d, 0x56, 0x7c, 0xb6, 0xe5, 0x26, 0x66, 0x62, 0xf8, 0x3d, 0x54, 0x26, 0x99, 0x09, 0x9e,
	0x78, 0x8e, 0x2a, 0x3d, 0xda, 0x6c, 0x96, 0x5a, 0x38, 0x19, 0x83, 0x7b, 0x33, 0x1c, 0xf3, 0x80,
	0xdd, 0x67, 0x73, 0x94, 0xb3, 0xa9, 0x23, 0x7c, 0x02, 0xae, 0xcc, 0xfa, 0xb2, 0x2e, 0xd7, 0x4b,
	0xa9, 0xf6, 0xa9, 0x41, 0x93, 0x97, 0xf0, 0x9f, 0x56, 0xa2, 0xfc, 0x2e, 0xe5, 0x89, 0x5c, 0x10,
	0x40, 0x8b, 0x02, 0xe4, 0x27, 0x82, 0x3d, 0x8b, 0x4c, 0xa2, 0x50, 0x24, 0xd9, 0x86, 0xba, 0x89,
	0xca, 0x28, 0xe8, 0xa6, 0xc9, 0x98, 0x42, 0x03, 0xc7, 0xa7, 0xe0, 0x26, 0x92, 0xc9, 0x34, 0x31,
	0xf7, 0x7f, 0x9c, 0x2f, 0xd4, 0x6f, 0xa4, 0x2d, 0x55, 0x40, 0x6a, 0x0a, 0xc8, 0x6b, 0xa8, 0x5f,
	0xc4, 0x9c, 0x49, 0xde, 0x65, 0x92, 0x0d, 0x58, 0xc2, 0xb7, 0xf9, 0xbe, 0x81, 0xc6, 0x72, 0x81,
	0xb1, 0x3f, 0x77, 0x81, 0xfe, 0xd5, 0xc5, 0x2b, 0x38, 0xe8, 0xc6, 0x61, 0xf4, 0xb7, 0x1e, 0x3e,
	0xc2, 0x61, 0x1e, 0x5e, 0xdc, 0x41, 0x1d, 0x0e, 0x2e, 0xb9, 0xb4, 0x8c, 0x89, 0x71, 0x40, 0x42,
	0x38, 0xcc, 0xa7, 0x8d, 0xd2, 0x53, 0xa8, 0x8e, 0x6c, 0xd2, 0x43, 0xcd, 0x52, 0xab, 0x4a, 0xe7,
	0x89, 0x22, 0xf7, 0xf1, 0x19, 0xb0, 0x1e, 0xaf, 0x5e, 0x2b, 0x33, 0x08, 0x0c, 0x4e, 0xf7, 0x7c,
	0xb6, 0xb7, 0xea, 0x8c, 0xdf, 0x42, 0x59, 0xed, 0x9c, 0xd1, 0xd8, 0xb6, 0xa0, 0x1a, 0x4c, 0xae,
	0xe1, 0x20, 0xc7, 0x5f, 0x7c, 0x72, 0x6d, 0x35, 0xa2, 0x2b, 0x16, 0x68, 0xca, 0x64, 0xdb, 0xe5,
	0xc5, 0x50, 0x5f, 0xc2, 0x1b, 0x0f, 0x47, 0x00, 0x19, 0xc0, 0xbc, 0x76, 0x7a, 0xa8, 0x0b, 0x99,
	0x22, 0x53, 0x3d, 0x83, 0xfd, 0x6c, 0x61, 0xb6, 0xce, 0x74, 0xcd, 0x9f, 0x16, 0xb9, 0x82, 0x47,
	0x0b, 0xf5, 0xc5, 0x67, 0xf6, 0x01, 0xfe, 0xbf, 0xe4, 0xf2, 0xc1, 0x76, 0x7e, 0x20, 0xd8, 0x9f,
	0xd7, 0x17, 0xb6, 0xf3, 0xb0, 0x55, 0x3a, 0x6f, 0x5c, 0xa3, 0x4f, 0xf7, 0x7c, 0x1a, 0x0c, 0x5c,
	0xf5, 0xf3, 0xe6, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x8e, 0x0e, 0xf5, 0x37, 0x08, 0x00,
	0x00,
}
